# 面積

面積を島リストに転記

In [51]:
import pandas as pd

islands_list_filepath = '../../data/raw/islands_list.xlsx'
islands_area_filepath = '../../data/raw/islands_area.xlsx'
prefecture_code_filepath = '../../data/processed/prefecuture_code.csv'
df_island_list = pd.read_excel(islands_list_filepath)
df_island_area = pd.read_excel(islands_area_filepath)
df_prefecture_code = pd.read_csv(prefecture_code_filepath)

In [52]:
df_island_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 218 entries, 0 to 217
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   island           218 non-null    object
 1   island_id        218 non-null    int64
 2   region_code      218 non-null    int64
 3   prefecture_code  218 non-null    int64
dtypes: int64(3), object(1)
memory usage: 6.9+ KB

In [62]:
df_island_area[df_island_area['island_name'] == '大島']

    island_name prefecture_name                            region_name   area
11           大島             愛媛県             今治市 (吉海町:津島を除く, 宮窪町:鵜島を除く)  41.88
45           大島             山口県                                萩市 (大島)   2.99
55           大島             高知県                               宿毛市 (大島)   1.01
59           大島             長崎県  佐世保市 (江上町の一部 [1700-01021～1700-01023])   0.52
117          大島             愛媛県        八幡浜市 (大島の一部 [0330-02010～03030])   0.75
149          大島             愛媛県                              新居浜市 (大島)   2.14
171          大島             長崎県                           壱岐市 (郷ノ浦町大島)   1.17
176          大島             大分県                             佐伯市 (大字大島)   1.61
200          大島             長崎県                             小値賀町 (大島郷)   0.68
211          大島             香川県        高松市 (庵治町の一部 [1630-00320～00370])   0.65

In [55]:
df_prefecture_code['prefecture_name'] = df_prefecture_code[' prefecture_name'].str.replace(' ', '')
df_prefecture_code

   prefecture_code  prefecture_name prefecture_name
0               32              島根県             島根県
1               33              岡山県             岡山県
2               34              広島県             広島県
3               35              山口県             山口県
4               36              徳島県             徳島県
5               37              香川県             香川県
6               38              愛媛県             愛媛県
7               39              高知県             高知県

In [56]:
df_merged_area_code = df_island_area.merge(df_prefecture_code[['prefecture_code', 'prefecture_name']], on='prefecture_name', how='left')
df_merged_area_code

,island_name,prefecture_name,region_name,area,prefecture_code
0,小豆島,香川県,"小豆島町, 土庄町 (沖島,小豊島,豊島を除く)",153.26,37.0
1,彦島,山口県,下関市 (彦島:竹ノ子島を除く),10.58,35.0
2,江田島・能美島,広島県,江田島市 (沖野島を除く),91.33,34.0
3,向島,広島県,"尾道市 (向島町:岩子島を除く, 向東町)",22.31,34.0
4,因島,広島県,"尾道市 (因島:因島原町,因島洲江町,細島を除く)",35.04,34.0
...,...,...,...,...,...
273,黒島 ※注,岡山県,瀬戸内市 (牛窓町牛窓の一部 [0870-13010]の一部),0.11,33.0
274,黄島,岡山県,瀬戸内市 (牛窓町牛窓の一部 [0870-13030]),0.43,33.0
275,猪子島,広島県,大竹市 (猪ノ子島),0.15,34.0
276,黒髪島・仙島 ※注,山口県,"周南市 (大字大津島字黒髪島, 大字富田の一部 [1330-21010])",5.36,35.0
277,比岐島 ※注,愛媛県,今治市 (今治村),0.23,38.0

In [57]:
# Merge the dataframes on the corresponding columns
df_merged = df_island_list.merge(
    df_merged_area_code[['island_name', 'area', 'prefecture_code']],
    left_on=['island', 'prefecture_code'],
    right_on=['island_name', 'prefecture_code'],
    how='left'
)

# Drop the redundant 'island_name' column
df_merged.drop(columns=['island_name'], inplace=True)

In [60]:
# Display the merged dataframe
df_merged.head()
output_filepath = '../../data/raw//merged_island_list.xlsx'
df_merged.to_excel(output_filepath, index=False)